name: Terraform Trigger

on:
  push:
    branches:
      - main
      - "feature/*"
  workflow_dispatch:

permissions:
  contents: read

env:
  TF_CLOUD_ORGANIZATION: "chrisnieves60"
  TF_WORKSPACE: "aws-terraform-ci-cd-2"

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Terraform Run
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
          -H "Content-Type: application/vnd.api+json" \
          -d '{"data": {"attributes": {"message": "Triggered by GitHub Actions"}, "type": "runs", "relationships": {"workspace": {"data": {"type": "workspaces", "id": "'"$TF_WORKSPACE"'"}}}}}' \
          https://app.terraform.io/api/v2/runs
