name: Terraform Deployment

on:
  push:
    branches:
      - main
      - "feature/*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: terraform init -backend-config="address=https://app.terraform.io/api/v2/workspaces/aws-terraform-ci-cd-2"

      - name: Terraform Plan
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: terraform apply -auto-approve tfplan
