name: Terraform Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_CLOUD_ORGANIZATION: "chrisnieves60"
  TF_WORKSPACE: "aws-terraform-ci-cd-2"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: terraform init

      - name: Plan Terraform
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: terraform plan -out=tfplan

      - name: Apply Terraform
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: terraform apply -auto-approve tfplan
