name: Terraform Trigger

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  TF_CLOUD_ORGANIZATION: "chrisnieves60"
  TF_WORKSPACE: "aws-terraform-ci-cd-2"

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Terraform Run
        run: |
          WORKSPACE_ID=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
            -H "Content-Type: application/vnd.api+json" \
            https://app.terraform.io/api/v2/organizations/chrisnieves60/workspaces/aws-terraform-ci-cd-2 | jq -r '.data.id')

          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
          -H "Content-Type: application/vnd.api+json" \
          -d '{
            "data": {
              "attributes": {
                "message": "Triggered by GitHub Actions"
              },
              "type": "runs",
              "relationships": {
                "workspace": {
                  "data": {
                    "type": "workspaces",
                    "id": "'"$WORKSPACE_ID"'"
                  }
                }
              }
            }
          }' \
          https://app.terraform.io/api/v2/runs
